# This is a test workflow
name: Node.js CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build
      env:
        ChromeAPI_clientId: ${{ secrets.CHROMEAPI_CLIENTID }}
        ChromeAPI_clientSecret: ${{ secrets.CHROMEAPI_CLIENTSECRET }}
        ChromeAPI_refreshToken: ${{ secrets.CHROMEAPI_REFRESHTOKEN }}
        extensionId: ${{ secrets.EXTENSIONID }}

